// <auto-generated />
namespace Argon2LoginWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201904061901294_UserDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
